# Generated by Django 5.2.4 on 2025-07-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_tracker', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='status',
            field=models.CharField(choices=[('Growing', 'Growing'), ('Harvested', 'Harvested')], default='Growing', max_length=20),
        ),
    ]
