# Generated by Django 5.2.4 on 2025-07-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_tracker', '0003_crop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='land_area',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='In acres or hectares', max_digits=10),
        ),
    ]
